org: t2minht
app: db-api
service: tasks

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
 name: aws
 runtime: python3.9
 region: us-east-1
 memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

