org: t2minht
app: db-api
service: tasks
frameworkVersion: '3'
provider:
 name: aws
 runtime: python3.9
 region: us-east-1
 memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
 wsgi:
   app: app
   packRequirements: false
functions:
  app:
   handler: wsgi.handler
   events:
     - http: ANY /

